# Generated by Django 5.2.7 on 2025-10-29 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_author_id_remove_book_id_remove_client_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='genrebook',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='genrebook',
            name='book',
        ),
        migrations.RemoveField(
            model_name='genrebook',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='purchase_id',
        ),
        migrations.AddField(
            model_name='author',
            name='book',
            field=models.ManyToManyField(to='store.book'),
        ),
        migrations.AddField(
            model_name='genre',
            name='book',
            field=models.ManyToManyField(to='store.book'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='AuthorBook',
        ),
        migrations.DeleteModel(
            name='GenreBook',
        ),
    ]
