# Generated by Django 5.2.7 on 2025-10-29 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_genrebook_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='id',
        ),
        migrations.AddField(
            model_name='purchase',
            name='purchase_id',
            field=models.AutoField(db_column='purchase_id', primary_key=True, serialize=False),
        ),
    ]
