# Generated by Django 5.2.7 on 2025-10-30 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_purchase_id_purchase_purchase_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasedetail',
            name='id',
        ),
        migrations.AlterField(
            model_name='purchasedetail',
            name='purchase',
            field=models.ForeignKey(db_column='purchase_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='store.purchase'),
        ),
    ]
