# Generated by Django 5.2.7 on 2025-10-30 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_purchase_id_purchase_purchase_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='purchasedetail',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='purchasedetail',
            constraint=models.UniqueConstraint(fields=('purchase', 'book'), name='unique_purchase_book'),
        ),
    ]
