# Generated by Django 5.2.7 on 2025-10-30 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_purchasedetail_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='purchasedetail',
            name='unique_purchase_book',
        ),
        migrations.AlterUniqueTogether(
            name='purchasedetail',
            unique_together={('purchase', 'book')},
        ),
        migrations.AlterField(
            model_name='purchasedetail',
            name='purchase',
            field=models.ForeignKey(db_column='purchase_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='store.purchase'),
        ),
        migrations.RemoveField(
            model_name='purchasedetail',
            name='id',
        ),
    ]
