# Generated by Django 5.2.7 on 2025-10-31 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_purchasedetail_unique_purchase_book_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'author_book',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GenreBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'genre_book',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='author',
            name='book',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(related_name='books', through='store.AuthorBook', to='store.author'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='book',
            field=models.ManyToManyField(related_name='genres', through='store.GenreBook', to='store.book'),
        ),
    ]
