# Generated by Django 5.2.7 on 2025-10-31 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_authorbook_genrebook_remove_author_book_book_author_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authorbook',
            options={},
        ),
        migrations.AlterModelOptions(
            name='genrebook',
            options={},
        ),
    ]
