# Generated by Django 5.2.7 on 2025-10-31 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_authorbook_options_alter_genrebook_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authorbook',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='genrebook',
            options={'managed': False},
        ),
    ]
